### ISSUE TITLE
the labels v.s. output of predict

### ISSUE THREAD

**Issue by jqlruc** [kieranjwood/trading-momentum-transformer#10]
Here is the output of the best model's prediction, which is positions: 
https://github.com/kieranjwood/trading-momentum-transformer/blob/d7df00bba31f5728e1c8bc735da0208892487142/mom_trans/deep_momentum_network.py#L474

But the labels that fit this model are "target_returns":
https://github.com/kieranjwood/trading-momentum-transformer/blob/d7df00bba31f5728e1c8bc735da0208892487142/mom_trans/model_inputs.py#L94C20-L94C20

why does the output of the fit have a different meaning from the output of the predicted function?

**Comment by jqlruc** [comment]
I got it, the output has a tanh activation:
https://github.com/kieranjwood/trading-momentum-transformer/blob/d7df00bba31f5728e1c8bc735da0208892487142/mom_trans/deep_momentum_network.py#L532

**Comment by danbo6** [comment]
Hi @jqlruc, I also feel this output is very confusing. please see https://github.com/kieranjwood/trading-momentum-transformer/blob/master/mom_trans/deep_momentum_network.py#L484, here the 'returns ' is a volatility scaled returns. Should we use the real daily return?
