### ISSUE TITLE
Possible Data Leakage in both CPD?

### ISSUE THREAD

**Issue by nova-land** [kieranjwood/trading-momentum-transformer#9]
Within the code in `mon_trans/changepoint_detection.py` at function `changepoint_loc_and_score`.

The script used the `StandardScaler` to fit transform the entire timeseries data, and I could not find anywhere else has a train/test split before generating CPD data. Is this a possible Data Leakage that improves the prediction result with CPD feature ?

```python
 time_series_data[["Y"]] = StandardScaler().fit(Y_data).transform(Y_data)
```

Best Regards,
Chris

**Comment by kieranjwood** [comment]
in this context, Y_data contains past day returns so it has already been observed, meaning there is no data leakage

**Comment by nova-land** [comment]
Confirmed with change point location normalisation only look at each window data.
